name: Clojure CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Clojure
      uses: DeLaGuardo/setup-clojure@master
      with:
        cli: 1.10.3.1040

    - name: Install clj-kondo
      run: npm install -g clj-kondo
      
    - name: Format 
      run: cd lab3/ && clojure -M:format
    
    - name: Lint
      run: cd lab3/ && clojure -M:lint

    - name: Run tests
      run: cd lab3/ && clojure -M:test
